import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { generatedShowcase } from './showcase.mjs';

export const root = new URL('../', import.meta.url);
export async function generatedCss() {
  const tokens = JSON.parse(await readFile(new URL('tokens/tokens.json', root), 'utf8'));
  const lines = [];
  for (const [group, entries] of Object.entries(tokens)) {
    for (const [name, token] of Object.entries(entries)) {
      if (typeof token.value !== 'string') throw new Error(`Invalid token: ${group}.${name}`);
      lines.push(`  --cap-${group}-${name}: ${token.value};`);
    }
  }
  return `/* Generated by npm run build. Edit tokens/tokens.json. */\n:root {\n${lines.join('\n')}\n}\n`;
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await writeFile(new URL('styles/tokens.css', root), await generatedCss());
  await writeFile(new URL('index.html', root), await generatedShowcase());
  console.log('Generated styles/tokens.css and index.html');
}
