import { readFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');

export async function generatedShowcase() {
  const catalog = JSON.parse(await readFile(new URL('assets/catalog.json', root), 'utf8'));
  const cards = await Promise.all(catalog.map(async asset => {
    const search = escape(`${asset.name.en} ${asset.name.es} ${asset.id} ${asset.family} ${asset.use?.join(" ") ?? ""}`);
    const preview = asset.family === 'interface'
      ? (await readFile(new URL(asset.master, root), 'utf8')).replace(/<title>.*?<\/title>/s, '').replace('<svg ', '<svg aria-hidden="true" ')
      : `<img src="${asset.master}" alt="" loading="lazy">`;
    const extra = asset.png ? `<a href="${asset.png}" download>PNG export</a>` : asset.png128 ? `<a href="${asset.png128}" download>PNG 128</a><a href="${asset.png256}" download>PNG 256</a><a href="${asset.tile}" download>Light tile</a>` : '';
    return `<article class="asset-card family-${asset.family}" data-family="${asset.family}" data-search="${search}"><div class="asset-stage">${preview}</div><div class="asset-info"><span class="eyebrow">${escape(asset.family === 'capptus-way' ? 'The Capptus Way' : asset.family === 'logo-proposal' ? 'Logo proposal' : asset.family)}</span>${asset.status?.startsWith('proposed') ? '<p class="asset-status">Proposal / Propuesta</p>' : ''}<h3>${escape(asset.name.en)}</h3><p class="asset-subtitle" lang="es">${escape(asset.name.es)}</p>${asset.use ? `<p class="asset-use">${escape(asset.use[1])}</p>` : ''}${asset.shortcode ? `<code>${escape(asset.shortcode)}</code>` : ''}<div class="asset-downloads"><a href="${asset.master}" download>${asset.master.endsWith('.png') ? 'Original PNG' : 'SVG master'}</a>${extra}</div></div></article>`;
  }));
  const colors = [['#008ED1', 'Capptus blue', 'Identity accent'], ['#6D6E70', 'Logo gray', 'Identity color'], ['#F8F7F3', 'Limestone', 'Warm surface'], ['#D8C5AB', 'Sand', 'Supporting surface'], ['#3B5146', 'Cactus', 'Deep support'], ['#1B1B19', 'Ink', 'Reading text']].map(([value, name, role]) => `<div class="swatch"><div class="color-chip" style="background:${value}" aria-hidden="true"></div><h3>${name}</h3><code>${value}</code><p>${role}</p></div>`).join('');
  const slides = [[1, 'Opening / atmosphere', 'Serif title, a quiet landscape, and a recognizable logo.'], [2, 'Question / focus', 'One question, generous space, and a single illustration.'], [6, 'System / explanation', 'The same visual language makes a complex lifecycle readable.'], [15, 'Transition / continuity', 'An editorial message paired with a human gesture.']].map(([page, title, caption]) => `<figure class="application"><a href="assets/applications/workshop-${String(page).padStart(2,'0')}.png"><img src="assets/applications/workshop-${String(page).padStart(2,'0')}.png" alt="Revenue OS workshop page ${page}: ${escape(title)}" loading="lazy" width="1600" height="900"></a><figcaption><strong>${title}</strong><span>${caption}</span><small>Workshop Cut · PDF page ${page}</small></figcaption></figure>`).join('');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="The Capptus design showcase: Living Oasis identity, original illustrations, compact emojis, interface icons, and presentation examples."><title>Capptus · Design showcase</title><link rel="icon" href="assets/emoji/bloom-128.png" type="image/png"><link rel="stylesheet" href="styles/tokens.css"><link rel="stylesheet" href="styles/typography.css"><link rel="stylesheet" href="styles/components.css"><link rel="stylesheet" href="styles/gallery.css"><script src="scripts/gallery.js" defer></script></head>
<body><a class="skip cap-button" href="#main">Skip to content</a><div class="shell"><header class="header"><a href="#main" aria-label="Capptus design showcase"><img class="logo" src="assets/logo/capptus-original.png" alt="Capptus" width="165"></a><nav aria-label="Showcase"><a href="#identity">Identity</a><a href="#capptus-way">Capptus Way</a><a href="#library">Asset library</a><a href="#in-use">In use</a><a href="#downloads">Downloads</a></nav></header>
<main id="main"><div class="hero"><div><p class="eyebrow">CAPPTUS DESIGN · THE LIVING OASIS</p><h1>One identity.<br>Room to <em>grow.</em></h1><p class="lead">The world we’re building for Capptus, brought together. From the original mark to small gestures and the way we tell a story.</p><div class="actions"><a class="cap-button" href="#library">Explore the collection <span aria-hidden="true">↗</span></a><a class="quiet-link" href="#in-use">See the system in use <span aria-hidden="true">↓</span></a></div></div><div class="hero-art"><img src="assets/illustrations/06-grow-together.png" alt="Three different botanical forms growing together, joined by a Capptus-blue line"><p class="eyebrow">ROOTED IN BAJA. OPEN TO POSSIBILITY.</p></div></div>
<div class="collection-index"><span>01 / Living Oasis direction</span><span>02 / ${catalog.length} reusable assets</span><span>03 / Presentation examples</span></div>
<section id="identity"><div class="section-head"><div><p class="eyebrow">01 / THE WORLD AROUND THE MARK</p><h2>Warmth. Clarity.<br>A little character.</h2></div><p>The original Capptus logo stays at the center. Editorial typography, warm surfaces, Baja-inspired imagery, and confident linework build the world around it.</p></div><a class="board-link" href="assets/reference/living-oasis-moodboard-v3.png"><img class="reference-board" src="assets/reference/living-oasis-moodboard-v3.png" alt="Living Oasis v3 moodboard with the original logo, palette, serif typography, desert imagery, and line illustration" loading="lazy" width="3600" height="2400"></a><div class="board-caption"><span>Living Oasis · Archived v3 study; typography predates the approved pairing</span><a class="quiet-link" href="downloads/Capptus-The-Living-Oasis-Moodboard-v3.svg" download>Download editable board ↗</a></div><div class="palette">${colors}</div><div class="type-pair"><div><p class="eyebrow">LORA · MEDIUM 500</p><p class="display-sample">Rooted in identity.<br>Open to <em>possibility.</em></p></div><div><p class="eyebrow">MONTSERRAT · REGULAR 400 / UI 500–600</p><h4>Clear words. A visible next step.</h4><p>Space for one dominant message, with straightforward reading text and quiet structure underneath.</p><p class="note">Approved pairing: Lora Medium for h1–h3, highlighted phrases, and quotations; Montserrat Regular for body text and Medium / SemiBold for UI. Emphasize one or two headline words with real Lora Italic.</p></div></div></section>
<section id="capptus-way"><div class="section-head"><div><p class="eyebrow">THE CAPPTUS WAY / LINE ART</p><h2>From first seed<br>to the next <em>growth.</em></h2></div><p>Six official delivery stages and a proposed Optimize / Grow extension. Black organic contours, open interiors, and restrained Capptus-blue and sand accents.</p></div><a class="board-link" href="assets/capptus-way/Capptus-Way-Set.png"><img class="reference-board" src="assets/capptus-way/Capptus-Way-Set.png" alt="Seven Capptus Way illustrations: Seedling Discover, Budding Design, Growing Build, Nurturing Integrate, Pruning Test Train, Harvest Deploy, and proposed Regrowth Optimize Grow; proposed cactus landscape logo" loading="lazy" width="1800" height="1320"></a><p class="note"><strong>Discover → Design → Build → Integrate → Test / Train → Deploy → Optimize / Grow.</strong> Regrowth / Rebrote is a proposed narrative name. Learning after go-live feeds Discover and Design. The logo shown is a proposal for The Capptus Way; the corporate Capptus logo remains unchanged.</p><div class="actions"><a class="cap-button" href="downloads/Capptus-Way-Icons-v1.zip" download>Download the Capptus Way kit ↗</a><a class="quiet-link" href="docs/capptus-way.md">Stage meanings and usage ↗</a></div></section>
<section id="library"><div class="section-head"><div><p class="eyebrow">02 / THE ASSET LIBRARY</p><h2>Small gestures.<br>Big personality.</h2></div><p>Seven Capptus Way illustrations and two logo proposals join eight original illustrations, eight compact emoji designs, and sixteen interface icons. Browse the actual artwork and download the files you need.</p></div><div class="library-toolbar"><div class="filters" role="group" aria-label="Asset family"><button type="button" data-family-filter="capptus-way" aria-pressed="false">Capptus Way <span>7</span></button><button type="button" data-family-filter="logo-proposal" aria-pressed="false">Logo proposals <span>2</span></button><button type="button" data-family-filter="all" aria-pressed="true">All <span>${catalog.length}</span></button><button type="button" data-family-filter="illustration" aria-pressed="false">Illustrations <span>8</span></button><button type="button" data-family-filter="emoji" aria-pressed="false">Emojis <span>8</span></button><button type="button" data-family-filter="interface" aria-pressed="false">Interface <span>16</span></button></div><label class="search-label" for="asset-search"><span>Search assets</span><input id="asset-search" type="search" placeholder="Search in English or Spanish"></label></div><p class="result-count" id="result-count" role="status">${catalog.length} assets</p><noscript><p>All assets are shown below. Search and filters require JavaScript.</p></noscript><div class="asset-grid">${cards.join('\n')}</div><p id="empty-state" hidden>No matching assets. Try another name or family.</p><div class="usage-strip"><p><strong>An illustration carries the story.</strong> Keep original art at a generous size.</p><p><strong>An emoji adds expression.</strong> Use compact artwork from 32px; keep light tiles on dark chat surfaces.</p><p><strong>An icon guides an action.</strong> Use 20–32px symbols within a labeled control.</p></div><p class="note">Shortcodes are proposed custom emoji names. Uploading to GitHub does not install them into messaging platforms. <a href="docs/icon-emoji-usage.txt">Read usage notes ↗</a></p></section>
<section id="in-use"><div class="section-head"><div><p class="eyebrow">03 / THE SYSTEM IN USE</p><h2>From a visual language<br>to real work.</h2></div><p>Selected layouts from the Revenue OS workshop show the same palette, typography, and illustration family working across a presentation.</p></div><div class="application-grid">${slides}</div><p class="note">Archived design excerpts from the supplied 17-page Workshop Cut; their rendered typography is preserved as source material. Client-specific working pages are kept outside this showcase.</p></section>
<section id="components"><div class="section-head"><div><p class="eyebrow">04 / DIGITAL FOUNDATIONS</p><h2>The everyday pieces.</h2></div><p>A small CSS foundation for bringing the same language into digital experiences. Action blue is darker than identity blue for readable text and controls.</p></div><div class="component-grid"><div class="component-sample"><p class="eyebrow">A CLEAR NEXT STEP</p><div class="actions"><a class="cap-button" href="#downloads">Get the assets ↗</a><a class="cap-button cap-button--secondary" href="#identity">Explore identity</a><button class="cap-button" type="button" disabled>Disabled</button></div><label class="cap-field" for="sample-name">Name<input class="cap-field__input" id="sample-name" type="text" placeholder="Your name" aria-describedby="sample-help"><span class="cap-field__help" id="sample-help">A component specimen. This field does not submit or save data.</span></label></div><div><article class="cap-card"><h3 class="cap-card__title">Room for the message.</h3><p class="cap-card__body">Quiet structure, one idea, and a clear reading order.</p></article><details class="cap-disclosure"><summary>How should the system evolve?</summary><p>Keep the logo intact. Use actual product needs to add components. Record decisions and check accessibility as the system grows.</p></details></div></div></section>
<section id="downloads"><div class="download-panel"><div><p class="eyebrow">05 / TAKE IT INTO YOUR WORK</p><h2>Ready to build with.</h2><p>Original artwork, editable SVGs, PNG exports, tokens, and usage guidance. Everything in one shared place.</p></div><div class="download-list"><a href="downloads/Capptus-Way-Icons-v1.zip" download><span>The Capptus Way kit</span><small>7 transparent PNGs · prompts · proposed SVG logo</small><b aria-hidden="true">↗</b></a><a href="downloads/Capptus-Icons-Emojis-v1.zip" download><span>Icon & emoji kit</span><small>Original ZIP · 24 SVG masters + PNG exports</small><b aria-hidden="true">↗</b></a><a href="downloads/Capptus-Icon-Emoji-System.svg" download><span>Icon & emoji reference sheet</span><small>Editable SVG board</small><b aria-hidden="true">↗</b></a><a href="tokens/tokens.json" download><span>Foundation tokens</span><small>Colors, typography, spacing, and controls</small><b aria-hidden="true">↗</b></a><a href="tokens/icon-emoji.tokens.json" download><span>Icon & emoji tokens</span><small>Grid, stroke, sizes, and motion</small><b aria-hidden="true">↗</b></a></div></div></section>
</main><footer><span>Capptus · Design showcase · October 2026</span><div><a href="README.md">Repository guide</a><a href="docs/provenance.md">Provenance</a><a href="https://github.com/luchein-lab/design">GitHub ↗</a></div></footer></div></body></html>\n`;
}
