import { readFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');

export async function generatedShowcase() {
  const catalog = JSON.parse(await readFile(new URL('assets/catalog.json', root), 'utf8'));
  const cards = await Promise.all(catalog.map(async asset => {
    const search = escape(`${asset.name.en} ${asset.name.es} ${asset.id} ${asset.family} ${asset.use?.join(" ") ?? ""}`);
    const preview = asset.family === 'interface'
      ? (await readFile(new URL(asset.master, root), 'utf8')).replace(/<title>.*?<\/title>/s, '').replace('<svg ', '<svg aria-hidden="true" ')
      : `<img src="${asset.master}" alt="" loading="lazy">`;
    const extra = asset.png ? `<a href="${asset.png}" download>PNG export</a>` : asset.png128 ? `<a href="${asset.png128}" download>PNG 128</a><a href="${asset.png256}" download>PNG 256</a>${asset.tile ? `<a href="${asset.tile}" download>Light tile</a>` : ''}` : '';
    return `<article class="asset-card family-${asset.family}" data-family="${asset.family}" data-search="${search}"><div class="asset-stage">${preview}</div><div class="asset-info"><span class="eyebrow">${escape(asset.family === 'capptus-way' ? 'The Capptus Way' : asset.family === 'compact' ? 'Compact icon' : asset.family)}</span>${asset.status?.startsWith('proposed') ? '<p class="asset-status">Proposal / Propuesta</p>' : ''}<h3>${escape(asset.name.en)}</h3><p class="asset-subtitle" lang="es">${escape(asset.name.es)}</p>${asset.use ? `<p class="asset-use">${escape(asset.use[1])}</p>` : ''}${asset.shortcode ? `<code>${escape(asset.shortcode)}</code>` : ''}<div class="asset-downloads"><a href="${asset.master}" download>${asset.master.endsWith('.png') ? 'Original PNG' : 'SVG master'}</a>${extra}</div></div></article>`;
  }));
  const colors = [['#008ED1', 'Capptus blue', 'Identity accent'], ['#6D6E70', 'Logo gray', 'Identity color'], ['#F8F7F3', 'Limestone', 'Warm surface'], ['#D8C5AB', 'Sand', 'Supporting surface'], ['#3B5146', 'Cactus', 'Deep support'], ['#1B1B19', 'Ink', 'Reading text']].map(([value, name, role]) => `<div class="swatch"><div class="color-chip" style="background:${value}" aria-hidden="true"></div><h3>${name}</h3><code>${value}</code><p>${role}</p></div>`).join('');
  const applications = [
    ['assets/applications/Capptus-Way-Executive-Diagram.png', 'Executive methodology diagram', 'The current Capptus Way illustrations explain six official delivery stages and a proposed growth loop.', 3840, 2160],
    ['assets/capptus-way/Capptus-Way-Primary-Blue-Large.png', 'Primary negative methodology logo', 'White linework and sand accents on Capptus blue establish the lead mark for the family.', 2400, 1200]
  ].map(([file, title, caption, width, height]) => `<figure class="application"><a href="${file}"><img src="${file}" alt="${escape(title)}" loading="lazy" width="${width}" height="${height}"></a><figcaption><strong>${title}</strong><span>${caption}</span></figcaption></figure>`).join('');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="The Capptus design showcase: Living Oasis identity, Capptus Way illustrations, compact icons, interface symbols, and presentation examples."><title>Capptus · Design showcase</title><link rel="icon" href="assets/icon-system-v2/compact/budding-128.png" type="image/png"><link rel="stylesheet" href="styles/tokens.css"><link rel="stylesheet" href="styles/typography.css"><link rel="stylesheet" href="styles/components.css"><link rel="stylesheet" href="styles/gallery.css"><script src="scripts/gallery.js" defer></script></head>
<body><a class="skip cap-button" href="#main">Skip to content</a><div class="shell"><header class="header"><a href="#main" aria-label="Capptus design showcase"><img class="logo" src="assets/logo/capptus-original.png" alt="Capptus" width="165"></a><nav aria-label="Showcase"><a href="#identity">Identity</a><a href="#capptus-way">Capptus Way</a><a href="#library">Asset library</a><a href="#in-use">In use</a><a href="#downloads">Downloads</a></nav></header>
<main id="main"><div class="hero"><div><p class="eyebrow">CAPPTUS DESIGN · THE LIVING OASIS</p><h1>One identity.<br>Room to <em>grow.</em></h1><p class="lead">The world we’re building for Capptus, brought together. From the original mark to small gestures and the way we tell a story.</p><div class="actions"><a class="cap-button" href="#library">Explore the collection <span aria-hidden="true">↗</span></a><a class="quiet-link" href="#in-use">See the system in use <span aria-hidden="true">↓</span></a></div></div><div class="hero-art"><img src="assets/capptus-way/03-growing-build.png" alt="Growing cactus illustration with Capptus-blue and sand accents"><p class="eyebrow">ROOTED IN BAJA. OPEN TO POSSIBILITY.</p></div></div>
<div class="collection-index"><span>01 / Current identity foundations</span><span>02 / ${catalog.length} reusable assets</span><span>03 / Presentation examples</span></div>
<section id="identity"><div class="section-head"><div><p class="eyebrow">01 / THE WORLD AROUND THE MARK</p><h2>Warmth. Clarity.<br>A little character.</h2></div><p>The original Capptus logo stays at the center. Editorial typography, warm surfaces, Baja-inspired imagery, and confident linework build the world around it.</p></div><div class="palette">${colors}</div><div class="type-pair"><div><p class="eyebrow">LORA · MEDIUM 500</p><p class="display-sample">Rooted in identity.<br>Open to <em>possibility.</em></p></div><div><p class="eyebrow">MONTSERRAT · REGULAR 400 / UI 500–600</p><h4>Clear words. A visible next step.</h4><p>Space for one dominant message, with straightforward reading text and quiet structure underneath.</p><p class="note">Approved pairing: Lora Medium for h1–h3, highlighted phrases, and quotations; Montserrat Regular for body text and Medium / SemiBold for UI. Emphasize one or two headline words with real Lora Italic.</p></div></div></section>
<section id="capptus-way"><div class="section-head"><div><p class="eyebrow">THE CAPPTUS WAY / METHODOLOGY</p><h2>From first seed<br>to the next <em>growth.</em></h2></div><p>Six official delivery stages, a proposed Optimize / Grow extension, and a learning loop that informs the next priorities. An executive diagram for methodology slides.</p></div><a class="board-link" href="assets/applications/Capptus-Way-Executive-Diagram.png"><img class="reference-board" src="assets/applications/Capptus-Way-Executive-Diagram.png" alt="Capptus Way executive diagram: Discover, Design, Build, Integrate, Test / Train, Deploy, with proposed Optimize / Grow returning learning to Discover and Design" loading="lazy" width="3840" height="2160"></a><p class="note"><strong>Discover → Design → Build → Integrate → Test / Train → Deploy → Optimize / Grow.</strong> The first six stages are official. Optimize / Grow and its Regrowth / Rebrote narrative name remain proposed.</p><div class="actions"><a class="cap-button" href="downloads/Capptus-Way-Executive-Diagram.pptx" download>Download editable slide ↗</a><a class="quiet-link" href="downloads/Capptus-Way-Executive-Diagram-Kit.zip" download>Diagram kit: PNG, SVG &amp; PPTX ↗</a><a class="quiet-link" href="docs/capptus-way.md">Stage meanings and usage ↗</a></div><h3>The primary methodology mark.</h3><a class="board-link" href="assets/capptus-way/Capptus-Way-Primary-Blue-Large.svg"><img class="reference-board" src="assets/capptus-way/Capptus-Way-Primary-Blue-Large.png" alt="Selected Capptus Way primary logo: circular cactus landscape beside white lettering on Capptus blue with sand accents" loading="lazy" width="2400" height="1200"></a><p class="note">The selected side-by-side negative lockup leads the methodology family. Use the transparent master on a dark brand surface or the blue version as a complete plate. The corporate Capptus logo is preserved.</p><div class="actions"><a class="cap-button" href="downloads/Capptus-Way-Primary-Negative-Kit.zip" download>Download primary logo kit ↗</a><a class="quiet-link" href="assets/capptus-way/Capptus-Way-Primary-Negative.svg" download>Transparent vector master ↗</a></div></section>
<section id="library"><div class="section-head"><div><p class="eyebrow">02 / THE ASSET LIBRARY · V2</p><h2>One family.<br>Three <em>scales.</em></h2></div><p>Seven Capptus Way illustrations, seven matching compact vector icons, and sixteen interface symbols. The reviewed v2 set brings the methodology into decks, websites, and documents.</p></div><a class="board-link" href="assets/reference/Capptus-Icon-System-v2.svg"><img class="reference-board" src="assets/reference/Capptus-Icon-System-v2.png" alt="Approved Capptus icon system v2: seven editorial methodology illustrations, seven matching compact vector icons, sixteen interface symbols, and the selected blue primary logo" loading="lazy" width="2400" height="2040"></a><div class="board-caption"><span>Approved v2 · Lora + Montserrat · Black linework with blue and sand accents</span><a class="quiet-link" href="downloads/Capptus-Icon-System-v2.zip" download>Download the complete v2 kit ↗</a></div><div class="library-toolbar"><div class="filters" role="group" aria-label="Asset family"><button type="button" data-family-filter="all" aria-pressed="true">All <span>${catalog.length}</span></button><button type="button" data-family-filter="capptus-way" aria-pressed="false">Illustrations <span>7</span></button><button type="button" data-family-filter="compact" aria-pressed="false">Compact icons <span>7</span></button><button type="button" data-family-filter="interface" aria-pressed="false">Interface <span>16</span></button></div><label class="search-label" for="asset-search"><span>Search assets</span><input id="asset-search" type="search" placeholder="Search in English or Spanish"></label></div><p class="result-count" id="result-count" role="status">${catalog.length} assets</p><noscript><p>All assets are shown below. Search and filters require JavaScript.</p></noscript><div class="asset-grid">${cards.join('\n')}</div><p id="empty-state" hidden>No matching assets. Try another name or family.</p><div class="usage-strip"><p><strong>An illustration carries the story.</strong> Use the original art at 128px or larger.</p><p><strong>A compact icon carries the motif.</strong> Use simplified vectors at 32–96px on light surfaces.</p><p><strong>An interface icon guides an action.</strong> Use 20–32px symbols within a labeled control.</p></div><p class="note">Six delivery stages are official. Optimize / Grow and Regrowth / Rebrote remain a proposed extension. <a href="docs/icon-emoji-usage.txt">Read v2 usage notes ↗</a> · <a href="docs/archive.md">Browse the archived v1 set ↗</a></p></section>
<section id="icon-prompt"><div class="section-head"><div><p class="eyebrow">CREATE IN THE CAPPTUS STYLE</p><h2>New ideas.<br>The same <em>language.</em></h2></div><p>Use the team master prompt to create industry symbols, flowchart concepts, and abstract ideas with the same organic linework, open interiors, and restrained color.</p></div><div class="component-grid"><article class="cap-card"><h3 class="cap-card__title">Regular</h3><p class="cap-card__body">Ink outlines with small Capptus-blue and sand accents. Open interiors on white or limestone.</p></article><article class="cap-card"><h3 class="cap-card__title">Negative</h3><p class="cap-card__body">White linework with sparse sand accents on Capptus blue. Preserve the same silhouette, proportions, and visual weight.</p></article></div><p class="note">The cactus inspires the drawing language; choose a recognizable subject for each concept. Keep work flat, with rounded lines and purposeful negative space.</p><div class="actions"><a class="cap-button" href="docs/icon-style-master-prompt.md">Read the master prompt ↗</a><a class="quiet-link" href="docs/icon-style-master-prompt.md" download>Download for the team ↗</a></div></section>
<section id="in-use"><div class="section-head"><div><p class="eyebrow">03 / THE SYSTEM IN USE</p><h2>From a visual language<br>to real work.</h2></div><p>The executive methodology diagram and selected primary logo show the current line-art family in use across presentation and brand assets.</p></div><div class="application-grid">${applications}</div><p class="note">Use the current v2 family and primary mark for new work. <a href="docs/archive.md">Earlier moodboards and workshop examples are available in the archive ↗</a>.</p></section>
<section id="components"><div class="section-head"><div><p class="eyebrow">04 / DIGITAL FOUNDATIONS</p><h2>The everyday pieces.</h2></div><p>A small CSS foundation for bringing the same language into digital experiences. Action blue is darker than identity blue for readable text and controls.</p></div><div class="component-grid"><div class="component-sample"><p class="eyebrow">A CLEAR NEXT STEP</p><div class="actions"><a class="cap-button" href="#downloads">Get the assets ↗</a><a class="cap-button cap-button--secondary" href="#identity">Explore identity</a><button class="cap-button" type="button" disabled>Disabled</button></div><label class="cap-field" for="sample-name">Name<input class="cap-field__input" id="sample-name" type="text" placeholder="Your name" aria-describedby="sample-help"><span class="cap-field__help" id="sample-help">A component specimen. This field does not submit or save data.</span></label></div><div><article class="cap-card"><h3 class="cap-card__title">Room for the message.</h3><p class="cap-card__body">Quiet structure, one idea, and a clear reading order.</p></article><details class="cap-disclosure"><summary>How should the system evolve?</summary><p>Keep the logo intact. Use actual product needs to add components. Record decisions and check accessibility as the system grows.</p></details></div></div></section>
<section id="downloads"><div class="download-panel"><div><p class="eyebrow">05 / TAKE IT INTO YOUR WORK</p><h2>Ready to build with.</h2><p>Original artwork, editable SVGs, PNG exports, tokens, and usage guidance. Everything in one shared place.</p></div><div class="download-list"><a href="docs/icon-style-master-prompt.md" download><span>Capptus icon master prompt</span><small>Regular + negative · industry symbols · flows · concepts</small><b aria-hidden="true">↗</b></a><a href="downloads/Capptus-Icon-System-v2.zip" download><span>Capptus icon system v2</span><small>7 illustrations · 7 compact SVGs + PNGs · 16 UI SVGs</small><b aria-hidden="true">↗</b></a><a href="assets/reference/Capptus-Icon-System-v2.svg" download><span>Current icon reference board</span><small>Self-contained SVG · outlined Lora + Montserrat</small><b aria-hidden="true">↗</b></a><a href="downloads/Capptus-Way-Executive-Diagram-Kit.zip" download><span>Executive methodology diagram</span><small>16:9 PNG · SVG · editable PPTX · font notices</small><b aria-hidden="true">↗</b></a><a href="downloads/Capptus-Way-Primary-Negative-Kit.zip" download><span>Primary Capptus Way logo</span><small>Transparent and blue versions · vector SVG + PNG</small><b aria-hidden="true">↗</b></a><a href="tokens/tokens.json" download><span>Foundation tokens</span><small>Colors, typography, spacing, and controls</small><b aria-hidden="true">↗</b></a><a href="tokens/icon-emoji.tokens.json" download><span>Icon system v2 tokens</span><small>Grid, stroke, sizes, and surface guidance</small><b aria-hidden="true">↗</b></a><a href="docs/archive.md"><span>Earlier design explorations</span><small>Archived v1 artwork, kits and metadata</small><b aria-hidden="true">↗</b></a></div></div></section>
</main><footer><span>Capptus · Design showcase · October 2026</span><div><a href="README.md">Repository guide</a><a href="docs/provenance.md">Provenance</a><a href="https://github.com/luchein-lab/design">GitHub ↗</a></div></footer></div></body></html>\n`;
}
